### ISSUE TITLE
SSL routines:SSL3_GET_RECORD:wrong version number  

### ISSUE THREAD

**Issue by ghost** [thisismedium/python-xmpp-server#1]
It seems that clients like pidgin and kopete use SSLv2. When trying to connect without modification, the server returns the following traceback:

ERROR:root:Exception in I/O handler for fd   7  
Traceback (most recent call last):  
File "/usr/local/lib/python2.6/dist-packages/tornado/ioloop.py", line 189, in start  
self._handlers[fd](fd, events)  
File "/usr/local/lib/python2.6/dist-packages/python_xmpp_server-0.1-py2.6.egg/xmpp/aio.py", line 202, in handshake    wrapped.do_handshake()  
File "/usr/lib/python2.6/ssl.py", line 293, in do_handshake  
  self._sslobj.do_handshake()  
SSLError: [Errno 1] _ssl.c:480: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

**Comment by thisismedium** [comment]
The starttls() handler has been updated to use SSLv23 instead of TLSv1.  Please give it another try.

**Comment by ghost** [comment]
Thank you for your quick response. I just confirmed that the SSL handler works fine now with both kopete and pidgin. Pidgin however asks for a certificate, which results in a SASL error: Server doesn't support "no layer"

**Comment by weaver** [comment]
Could the prompt about a certificate be due to the fact that the certificates in the example are self-signed?

**Comment by fpietrosanti** [comment]
We are still keeping this error on pidgin + python 2.6
